#An e-commerce company exports its daily order log in the following format. Each order contains multiple pieces of information:

#python
orders = [
    ["ORD001","Laptop",75000,"Completed"],
    ["ORD002","Mouse",500,"Completed"],
    ["ORD003","Laptop",75000,"Returned"],
    ["ORD004","Keyboard",1500,"Completed"],
    ["ORD005","Laptop",75000,"Completed"],
    ["ORD006","Monitor",20000,"Fraud"],
    ["ORD007","Mouse",500,"Completed"],
    ["ORD008","Laptop",75000,"Completed"]
]
#Each row represents an order with the following structure:

#[Order_ID , Product_Name , Price , Status]

#Where:

#Order_ID → unique order identifier

#Product_Name → product purchased

#Price → price of the product

#Status → order status (Completed, Returned, Fraud)

#Your Task:  
#Write a Python program to simulate a simple order analysis system using loops, nested loops, conditional statements, and list operations.
#Your program must perform the following steps:             

#Display All Orders
#Using a nested loop, print the entire order table row by row so that each order’s details are displayed clearly.

for order in orders:
    for detail in order:
        print(detail, end=" | ")
    print()

#Detect Suspicious Activity
#The system suspects fraud when: the same product appears more than 3 times, OR an order has status "Fraud".
#Write a program that scans the dataset and identifies suspicious products or orders. You must use nested loops to compare product occurrences. Print the Order_IDs of suspicious orders and the names of suspicious products.

suspicious_orders = []
suspicious_products = []

# Check for fraud status and product occurrences
for order in orders:
    if order[3] == "Fraud":
        suspicious_orders.append(order[0])
    product_count = 0
    for inner_order in orders:
        if inner_order[1] == order[1]:
            product_count += 1
    if product_count > 3:
        suspicious_products.append(order[1])

print("Suspicious Orders:", suspicious_orders)
print("Suspicious Products:", suspicious_products)

#Calculate Total Revenue
#Only Completed orders contribute to revenue. Write code that iterates through the dataset, adds the price of all completed orders, and prints the total revenue generated for the day.

total_revenue = 0
for order in orders:
    if order[3] == "Completed":
        total_revenue += order[2]
print("Total Revenue:", total_revenue)

#Count Order Types
#Using loops and conditional statements, count how many orders fall into each category: Completed, Returned, Fraud.
#Store these counts in separate variables.
completed_count = 0
returned_count = 0
fraud_count = 0

for order in orders:
    if order[3] == "Completed":
        completed_count += 1
    elif order[3] == "Returned":
        returned_count += 1
    elif order[3] == "Fraud":
        fraud_count += 1

#Generate a List of Unique Products
#Create a new list containing unique product names present in the dataset. You must implement this without using the set() function.
unique_products = []
for order in orders:
    product_name = order[1]
    if product_name not in unique_products:
        unique_products.append(product_name)

#Product Sales Analysis
#For each unique product, determine how many times it was ordered and the total revenue generated by that product. This requires nested loops.
product_sales = {}
for product in unique_products:
    product_sales[product] = {"count": 0, "revenue": 0}
    for order in orders:
        if order[1] == product:
            product_sales[product]["count"] += 1
            if order[3] == "Completed":
                product_sales[product]["revenue"] += order[2]

#Identify the Most Sold Product
#Based on the frequency of orders, determine which product appears the most in the dataset.
product_count = {}
for order in orders:
    product_name = order[1]
    if product_name in product_count:
        product_count[product_name] += 1
    else:
        product_count[product_name] = 1

most_sold_product = max(product_count, key=product_count.get)
print("Most Sold Product:", most_sold_product)

#Remove Fraud Orders
#Create a cleaned dataset by removing orders whose status is "Fraud". Use list methods to store the cleaned data in a new list.
cleaned_orders = []
for order in orders:
    if order[3] != "Fraud":
        cleaned_orders.append(order)